/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewyearRouteImport } from './routes/newyear'
import { Route as IndexRouteImport } from './routes/index'

const NewyearRoute = NewyearRouteImport.update({
  id: '/newyear',
  path: '/newyear',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newyear': typeof NewyearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/newyear': typeof NewyearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/newyear': typeof NewyearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/newyear'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/newyear'
  id: '__root__' | '/' | '/newyear'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewyearRoute: typeof NewyearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/newyear': {
      id: '/newyear'
      path: '/newyear'
      fullPath: '/newyear'
      preLoaderRoute: typeof NewyearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewyearRoute: NewyearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
